name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Select latest Xcode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

    - name: Build project
      run: xcodebuild -scheme "Metafile to ESP Converter for Mac" -sdk macosx build
